//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedVMConfig) DeepCopyInto(out *AdvancedVMConfig) {
	*out = *in
	if in.DiskEnableUUID != nil {
		in, out := &in.DiskEnableUUID, &out.DiskEnableUUID
		*out = new(bool)
		**out = **in
	}
	if in.NestedVirtualization != nil {
		in, out := &in.NestedVirtualization, &out.NestedVirtualization
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedVMConfig.
func (in *AdvancedVMConfig) DeepCopy() *AdvancedVMConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedVMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentISOSpec) DeepCopyInto(out *AgentISOSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentISOSpec.
func (in *AgentISOSpec) DeepCopy() *AgentISOSpec {
	if in == nil {
		return nil
	}
	out := new(AgentISOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialReference) DeepCopyInto(out *CredentialReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialReference.
func (in *CredentialReference) DeepCopy() *CredentialReference {
	if in == nil {
		return nil
	}
	out := new(CredentialReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolReference) DeepCopyInto(out *NodePoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolReference.
func (in *NodePoolReference) DeepCopy() *NodePoolReference {
	if in == nil {
		return nil
	}
	out := new(NodePoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMStatus) DeepCopyInto(out *VMStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMStatus.
func (in *VMStatus) DeepCopy() *VMStatus {
	if in == nil {
		return nil
	}
	out := new(VMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMTemplateSpec) DeepCopyInto(out *VMTemplateSpec) {
	*out = *in
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdvancedConfig != nil {
		in, out := &in.AdvancedConfig, &out.AdvancedConfig
		*out = new(AdvancedVMConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMTemplateSpec.
func (in *VMTemplateSpec) DeepCopy() *VMTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VMTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareNodePoolTemplate) DeepCopyInto(out *VMwareNodePoolTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareNodePoolTemplate.
func (in *VMwareNodePoolTemplate) DeepCopy() *VMwareNodePoolTemplate {
	if in == nil {
		return nil
	}
	out := new(VMwareNodePoolTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMwareNodePoolTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareNodePoolTemplateList) DeepCopyInto(out *VMwareNodePoolTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMwareNodePoolTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareNodePoolTemplateList.
func (in *VMwareNodePoolTemplateList) DeepCopy() *VMwareNodePoolTemplateList {
	if in == nil {
		return nil
	}
	out := new(VMwareNodePoolTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMwareNodePoolTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareNodePoolTemplateSpec) DeepCopyInto(out *VMwareNodePoolTemplateSpec) {
	*out = *in
	if in.NodePoolRef != nil {
		in, out := &in.NodePoolRef, &out.NodePoolRef
		*out = new(NodePoolReference)
		**out = **in
	}
	if in.VSphereCredentials != nil {
		in, out := &in.VSphereCredentials, &out.VSphereCredentials
		*out = new(CredentialReference)
		**out = **in
	}
	in.VMTemplate.DeepCopyInto(&out.VMTemplate)
	out.AgentISO = in.AgentISO
	if in.AgentLabelSelector != nil {
		in, out := &in.AgentLabelSelector, &out.AgentLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareNodePoolTemplateSpec.
func (in *VMwareNodePoolTemplateSpec) DeepCopy() *VMwareNodePoolTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VMwareNodePoolTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMwareNodePoolTemplateStatus) DeepCopyInto(out *VMwareNodePoolTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VMStatus != nil {
		in, out := &in.VMStatus, &out.VMStatus
		*out = make([]VMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMwareNodePoolTemplateStatus.
func (in *VMwareNodePoolTemplateStatus) DeepCopy() *VMwareNodePoolTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VMwareNodePoolTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
